---
- name: Create custom_components/ directory
  file:
    path: "{{ homeassistantfrigate_required_volumes.config }}/custom_components/"
    state: directory
    owner: root
    group: root
  become: true

- name: Download BambuLab custom component
  git:
    repo: "https://github.com/greghesp/ha-bambulab"
    dest: /tmp/ansible-role-homeassistant-frigate/bambu_lab
    depth: 1

- name: Install BambuLab custom component
  copy:
    src: /tmp/ansible-role-homeassistant-frigate/bambu_lab/custom_components/bambu_lab
    dest: "{{ homeassistantfrigate_required_volumes.config }}/custom_components/"
  become: true

- name: Download Frigate custom component
  git:
    repo: "https://github.com/blakeblackshear/frigate-hass-integration"
    dest: /tmp/ansible-role-homeassistant-frigate/frigate
    depth: 1

- name: Install Frigate custom component
  copy:
    src: /tmp/ansible-role-homeassistant-frigate/frigate/custom_components/frigate
    dest: "{{ homeassistantfrigate_required_volumes.config }}/custom_components/"
  become: true

- name: Download Meross custom component
  git:
    repo: "https://github.com/albertogeniola/meross-homeassistant"
    dest: /tmp/ansible-role-homeassistant-frigate/meross
    depth: 1

- name: Install Meross custom component
  copy:
    src: /tmp/ansible-role-homeassistant-frigate/meross/custom_components/meross_cloud
    dest: "{{ homeassistantfrigate_required_volumes.config }}/custom_components/"
  become: true

- name: Download Roborock custom component
  get_url:
    url: 'https://github.com/humbertogontijo/homeassistant-roborock/releases/latest/download/roborock.zip'
    dest: /tmp/roborock-custom-component.zip

- name: Create Roborock custom component directory
  ansible.builtin.file:
    path: "{{ homeassistantfrigate_required_volumes.config }}/custom_components/roborock"
    state: directory
    mode: '0755'
  become: true

- name: Install Roborock custom component
  ansible.builtin.unarchive:
    src: /tmp/roborock-custom-component.zip
    dest: "{{ homeassistantfrigate_required_volumes.config }}/custom_components/roborock"
    # Drop the ./dist directory
    # -j junk  paths. The  archive's directory structure is not recreated;
    # all files are deposited in the extraction directory (by default, the current one).
    #extra_opts: '-j'
  become: true

- name: Download Simple Icons custom component
  git:
    repo: "https://github.com/vigonotion/hass-simpleicons"
    dest: /tmp/ansible-role-homeassistant-frigate/simpleicons
    depth: 1

- name: Install Simple Icons custom component
  copy:
    src: /tmp/ansible-role-homeassistant-frigate/simpleicons/custom_components/simpleicons
    dest: "{{ homeassistantfrigate_required_volumes.config }}/custom_components/"
  become: true

- name: Copy python_scripts/ directory
  copy:
    src: homeassistant/python_scripts/
    dest: "{{ homeassistantfrigate_required_volumes.config }}/python_scripts/"
  become: true
