---
- name: Create www/ directory
  file:
    path: "{{ homeassistantfrigate_required_volumes.config }}/www/"
    state: directory
    owner: root
    group: root
  become: true

- name: Get the latest Frigate card version
  uri:
    url: https://api.github.com/repos/dermotduffy/frigate-hass-card/releases/latest
    return_content: "yes"
  register: frigate_card_version

- name: Download Frigate card
  get_url:
    url: https://github.com/dermotduffy/frigate-hass-card/releases/download/{{ frigate_card_version.json.tag_name }}/frigate-hass-card.zip
    dest: /tmp/frigate-hass-card.zip

- name: Create frigate-hass-card directory
  ansible.builtin.file:
    path: "{{ homeassistantfrigate_required_volumes.config }}/www/frigate-hass-card"
    state: directory
    mode: '0755'
  become: true

- name: Install Frigate card
  ansible.builtin.unarchive:
    src: /tmp/frigate-hass-card.zip
    dest: "{{ homeassistantfrigate_required_volumes.config }}/www/frigate-hass-card"
    # Drop the ./dist directory
    # -j junk  paths. The  archive's directory structure is not recreated;
    # all files are deposited in the extraction directory (by default, the current one).
    extra_opts: '-j'
  become: true

- name: Install Layout Card plugin
  get_url:
    url: https://raw.githubusercontent.com/thomasloven/lovelace-layout-card/master/layout-card.js
    dest: "{{ homeassistantfrigate_required_volumes.config }}/www/"
  become: true

- name: Install Slider Entry Row card
  get_url:
    url: https://raw.githubusercontent.com/thomasloven/lovelace-slider-entity-row/master/slider-entity-row.js
    dest: "{{ homeassistantfrigate_required_volumes.config }}/www/"
  become: true
