---
- name: Create www/ directory
  file:
    path: "{{ homeassistantfrigate_required_volumes.config }}/www/"
    state: directory
    owner: root
    group: root
  become: true

- name: Get the latest Frigate card version
  uri:
    url: https://api.github.com/repos/dermotduffy/frigate-hass-card/releases/latest
    return_content: "yes"
  register: frigate_card_version

- name: Install Frigate card
  get_url:
    url: https://github.com/dermotduffy/frigate-hass-card/releases/download/{{ frigate_card_version.json.tag_name }}/frigate-hass-card.js
    dest: "{{ homeassistantfrigate_required_volumes.config }}/www/"
  become: true

- name: Install Slider Entry Row card
  get_url:
    url: https://raw.githubusercontent.com/thomasloven/lovelace-slider-entity-row/master/slider-entity-row.js
    dest: "{{ homeassistantfrigate_required_volumes.config }}/www/"
  become: true
