# https://docs.frigate.video/configuration/index/
birdseye:
  mode: continuous
cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://example.com:554/cam/realmonitor?channel=1&subtype=0
          # NOTICE: In addition to assigning the record, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect
            - record
            - rtmp
    motion:
      mask:
        - 0,614,0,0,186,0,206,153,64,406
    objects:
      track:
        - bicycle
        - bus
        - car
        - cat
        - dog
        - motorcycle
        - person
  kid:
    ffmpeg:
      inputs:
        - path: rtsp://example.com:443/videoMain
          roles:
            - detect
            - rtmp
    record:
      enabled: False
    snapshots:
      enabled: False
detect:
  enabled: True
detectors:
  coral:
    type: cpu
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -use_wallclock_as_timestamps
    - "1"
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  # threshold: 25 # (default)
  threshold: 50
mqtt:
  host: example.com
objects:
  filters:
    person:
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive
      threshold: 0.72
  # Optional: list of objects to track from labelmap.txt
  track:
    - person # Default: person only
    - cat
    - dog
record:
  enabled: True
  retain_days: 0
  events:
    # Optional: Maximum length of time to retain video during long events.
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain_days under record is > 0.
    max_seconds: 1200
    # Optional: Number of seconds before the event to include
    pre_capture: 10
    # Optional: Number of seconds after the event to include
    post_capture: 10
    retain:
      default: 60
rtmp:
  enabled: True
snapshots:
  enabled: True
  bounding_box: False
  timestamp: True
  retain:
    default: 60
timestamp_style:
  # "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tr"
  format: "%Y-%m-%d %H:%M:%S"
